package com.dndsaas.service

import com.dndsaas.dto.LlmRequest
import com.dndsaas.dto.LlmResult
import com.dndsaas.dto.TokenUsage
import org.slf4j.LoggerFactory

/**
 * A stand-in for a real model.
 *
 * Used automatically when no API key is configured, and available on demand via
 * `"mock": true` so the whole pipeline — context collection, prompt building,
 * validation and persistence — can be exercised without spending tokens.
 *
 * It inspects the requested JSON schema and returns a plausibly shaped reply,
 * so generators can be tested end to end.
 */
class MockLlmClient : LlmClient {

    private val log = LoggerFactory.getLogger(MockLlmClient::class.java)

    override val providerName: String = "Mock"

    override fun complete(request: LlmRequest): LlmResult {
        val prompt = request.messages.joinToString("\n") { it.content }
        log.info("MockLlmClient invoked (no tokens spent), prompt length={} chars", prompt.length)

        val content = when {
            !request.jsonMode -> "Mock response. The pipeline ran end to end using ${prompt.length} characters of prompt."
            prompt.contains("\"questions\"") -> interviewJson()
            prompt.contains("\"worldLore\"") -> campaignBlueprintJson()
            prompt.contains("\"previouslyOn\"") -> nextSessionJson()
            prompt.contains("\"idea\"") -> """{ "idea": "A mock idea: a lighthouse keeper hires the party to guard a light that attracts ships from other worlds.", "tone": "eerie, hopeful", "themes": "isolation, duty, the unknown", "length": 5 }"""
            // Each generator's schema has a key no other schema uses.
            prompt.contains("\"connectionsToWorld\"") -> backstoryJson()
            prompt.contains("\"hoardDescription\"") -> lootJson()
            prompt.contains("\"howToUse\"") -> randomEncounterJson()
            prompt.contains("\"setup\"") -> encounterJson()
            prompt.contains("\"complication\"") -> questJson()
            prompt.contains("\"solution\"") -> puzzleJson()
            else -> genericJson(prompt.length)
        }

        // Rough estimate: ~4 characters per token.
        val promptTokens = prompt.length / 4
        val completionTokens = content.length / 4
        return LlmResult(
            content = content,
            usage = TokenUsage(promptTokens, completionTokens, promptTokens + completionTokens),
            model = "mock",
            mocked = true,
        )
    }

    private fun genericJson(promptLength: Int) = """
        {
          "name": "Mock the Placeholder",
          "summary": "Generated by MockLlmClient because no OpenAI key was used.",
          "description": "This response proves the pipeline ran end to end: campaign context was collected, a prompt was built, a client was called, and the reply was validated.",
          "promptCharacters": $promptLength
        }
    """.trimIndent()

    private fun backstoryJson() = """
        {
          "backstory": "A mock backstory produced without calling OpenAI. The character grew up on the edge of the map, where the roads stop being roads.\n\nThey left home after a promise went unkept, and have been trying to keep a different one ever since.",
          "hook": "Someone from their past has just arrived in town asking questions.",
          "connectionsToWorld": "Ties to the campaign's existing locations would appear here.",
          "newNpcs": [
            {
              "name": "Mock Mentor",
              "relationshipToCharacter": "mentor",
              "description": "A patient teacher with a secret.",
              "motivation": "To see the student finish what they could not.",
              "locationName": null
            }
          ]
        }
    """.trimIndent()

    private fun lootJson() = """
        {
          "hoardDescription": "A dented chest, half-buried in mock ash.",
          "currency": "120 gp and a silver locket worth 25 gp",
          "items": [
            {
              "name": "Mockblade",
              "type": "Weapon",
              "rarity": "UNCOMMON",
              "description": "A plain longsword that hums faintly.",
              "properties": "+1 to attack and damage rolls.",
              "history": "Forged for testing, never for war.",
              "requiresAttunement": false
            }
          ],
          "locationName": null
        }
    """.trimIndent()

    private fun questJson() = """
        {
          "title": "The Mock Errand",
          "description": "A placeholder quest produced without calling OpenAI.",
          "hook": "A nervous courier asks the party for help.",
          "objective": "Deliver a sealed letter before nightfall.",
          "reward": "50 gp and a favour owed",
          "questGiverName": null,
          "locationName": null,
          "involvedNpcNames": [],
          "complication": "The letter is addressed to someone who died a year ago.",
          "status": "AVAILABLE"
        }
    """.trimIndent()

    private fun encounterJson() = """
        {
          "title": "Mock Ambush",
          "description": "Bandits wait where the road narrows.",
          "objective": "Get the wagon through the pass.",
          "terrain": "A rocky pass with boulders for cover and a steep drop on one side.",
          "setup": "Stones clatter down the slope. Figures rise from behind the rocks.",
          "resolution": "The bandits flee once their captain falls.",
          "creatures": [
            { "name": "Bandit", "count": 4, "challengeRating": "1/8", "role": "MINION", "tactics": "Swarm the nearest target." },
            { "name": "Bandit Captain", "count": 1, "challengeRating": "2", "role": "LEADER", "tactics": "Stays back and directs the others." }
          ],
          "locationName": null
        }
    """.trimIndent()

    private fun randomEncounterJson() = """
        {
          "region": "The roads around the campaign's starting area",
          "howToUse": "Roll a d6 once per watch while travelling.",
          "encounters": [
            { "roll": "1", "title": "Wolves", "description": "A hungry pack circles the camp.", "type": "COMBAT", "creatures": "Wolf x3", "twist": "One wolf wears a collar." },
            { "roll": "2", "title": "Lost Pilgrim", "description": "A pilgrim asks the way to a shrine.", "type": "SOCIAL", "creatures": "", "twist": "The shrine does not exist." },
            { "roll": "3", "title": "Collapsed Bridge", "description": "The bridge ahead is gone.", "type": "HAZARD", "creatures": "", "twist": "It was cut deliberately." }
          ]
        }
    """.trimIndent()

    private fun puzzleJson() = """
        {
          "name": "The Mock Door",
          "presentation": "A stone door with three dials: sun, moon and star.",
          "mechanism": "The dials must match the order of the murals in the hall.",
          "solution": "Moon, star, sun.",
          "hints": ["The murals tell a story.", "The story begins at night.", "Moon first."],
          "alternativeSolutions": ["Forcing the door with a DC 20 Strength check"],
          "failureConsequence": "The dials reset and a chime echoes down the hall.",
          "bypass": "A narrow crawlspace behind the murals.",
          "skillChecks": ["Intelligence (Investigation) DC 12 to notice the mural order"]
        }
    """.trimIndent()

    private fun nextSessionJson() = """
        {
          "title": "Mock Session: The Morning After",
          "previouslyOn": "Last time, you followed the ash trail into the hills and found the furnace door warm to the touch.",
          "summary": "The party deals with the consequences of what they found at the end of the last session.",
          "openingScene": "Dawn breaks grey over the vale. The furnace door you left behind is open.",
          "beats": ["The village wakes to find the door open", "A familiar NPC asks for help", "The trail leads underground"],
          "encounters": ["Social: calm the frightened villagers", "Combat: whatever came out of the furnace"],
          "cliffhanger": "A voice from the dark calls one of the characters by name.",
          "dmTips": ["Let the players' choices from last session shape how the villagers react."]
        }
    """.trimIndent()

    private fun interviewJson() = """
        {
          "understanding": "A mock paraphrase of your idea, produced without calling OpenAI.",
          "questions": [
            {
              "id": "central_conflict",
              "question": "What is the central conflict driving this campaign?",
              "why": "It determines the shape of every quest.",
              "suggestedAnswers": ["A looming invasion", "A political conspiracy", "An awakening ancient evil"]
            },
            {
              "id": "villain_goal",
              "question": "What does the villain actually want?",
              "why": "A concrete goal makes the villain feel active rather than decorative.",
              "suggestedAnswers": ["Immortality", "Revenge on a bloodline", "To rewrite history"]
            },
            {
              "id": "party_stake",
              "question": "Why is this party the one that has to deal with it?",
              "why": "It ties the players personally into the story.",
              "suggestedAnswers": ["They are the only witnesses", "They are blamed for it", "They are bound by an oath"]
            }
          ]
        }
    """.trimIndent()

    private fun campaignBlueprintJson() = """
        {
          "name": "The Mock Campaign",
          "premise": "A placeholder campaign produced without calling OpenAI, so the full pipeline can be tested for free.",
          "worldLore": "This world exists only to prove that generated content is written into Campaign Memory as structured rows. The Ashen Vale is a shuttered valley where a mock cult stirs. Its people remember a fire that never went out, and the roads out lead only back in.",
          "tone": "Testing, faintly ominous",
          "locations": [
            {
              "name": "The Ashen Vale",
              "type": "REGION",
              "description": "A valley of grey fields under a permanently overcast sky.",
              "atmosphere": "Fine ash on every surface; the smell of old smoke.",
              "parentName": null
            },
            {
              "name": "Cinderhollow",
              "type": "VILLAGE",
              "description": "The last inhabited settlement in the vale.",
              "atmosphere": "Shuttered windows and cold hearths.",
              "parentName": "The Ashen Vale"
            }
          ],
          "factions": [
            {
              "name": "The Ember Circle",
              "type": "Cult",
              "description": "Keepers of a fire they will not let die.",
              "goals": "Rekindle the old flame beneath the vale.",
              "ideology": "Ash is only fire that is waiting.",
              "headquartersName": "Cinderhollow"
            }
          ],
          "npcs": [
            {
              "name": "Vessa Coalwright",
              "race": "Human",
              "occupation": "Innkeeper",
              "role": "Quest giver",
              "description": "Runs the only inn still serving hot food.",
              "appearance": "Soot-stained apron, burn scars along both forearms.",
              "personality": "Blunt, generous, tired.",
              "motivation": "Keep Cinderhollow alive one more winter.",
              "secret": "She was once a member of the Ember Circle.",
              "voice": "Low and flat, never wastes a word.",
              "locationName": "Cinderhollow",
              "factionName": null
            },
            {
              "name": "Warden Ilric",
              "race": "Human",
              "occupation": "Cult warden",
              "role": "Villain",
              "description": "Speaks for the Ember Circle in public.",
              "appearance": "Immaculate grey robes that never gather ash.",
              "personality": "Patient, courteous, immovable.",
              "motivation": "Complete the rekindling before the vale empties.",
              "secret": "The rekindling requires the village itself as fuel.",
              "voice": "Warm and reasonable, which is worse.",
              "locationName": "Cinderhollow",
              "factionName": "The Ember Circle"
            }
          ],
          "quests": [
            {
              "title": "The Cold Hearth",
              "description": "Vessa's hearth will not light, and nor will any other in the village.",
              "hook": "The innkeeper offers free lodging to anyone who can explain it.",
              "objective": "Discover why fire no longer takes in Cinderhollow.",
              "reward": "Shelter, supplies, and Vessa's trust.",
              "questGiverName": "Vessa Coalwright",
              "locationName": "Cinderhollow",
              "involvedNpcNames": ["Vessa Coalwright", "Warden Ilric"]
            }
          ],
          "firstSession": {
            "title": "Ash on the Road",
            "summary": "The party arrives in Cinderhollow as the last hearth goes cold.",
            "openingScene": "The ash starts before the border stone. By the time you reach the village gate it is over your boots, and no chimney in sight is smoking.",
            "beats": [
              "Arrival at the village gate and the unnatural silence",
              "Vessa offers food she cannot heat, and asks for help",
              "Warden Ilric introduces himself far too pleasantly",
              "A child is found sleepwalking toward the old furnace"
            ],
            "encounters": [
              "Social: Warden Ilric probes what the party knows",
              "Exploration: the sealed furnace beneath the village"
            ],
            "cliffhanger": "The furnace door is warm to the touch, and something inside knocks back.",
            "dmTips": [
              "Play Ilric as helpful; let the players decide he is wrong.",
              "Keep the cold hearths constant so the payoff lands."
            ]
          }
        }
    """.trimIndent()
}
