package com.dndsaas.service

import com.dndsaas.dto.LlmRequest
import com.dndsaas.dto.LlmResult
import com.dndsaas.dto.TokenUsage
import org.slf4j.LoggerFactory

/**
 * A stand-in for a real model.
 *
 * Used automatically when no API key is configured, and available on demand via
 * `"mock": true` so the whole pipeline — context collection, prompt building,
 * validation and persistence — can be exercised without spending tokens.
 *
 * It inspects the requested JSON schema and returns a plausibly shaped reply,
 * so generators can be tested end to end.
 */
class MockLlmClient : LlmClient {

    private val log = LoggerFactory.getLogger(MockLlmClient::class.java)

    override val providerName: String = "Mock"

    override fun complete(request: LlmRequest): LlmResult {
        val prompt = request.messages.joinToString("\n") { it.content }
        log.info("MockLlmClient invoked (no tokens spent), prompt length={} chars", prompt.length)

        val content = when {
            !request.jsonMode -> "Mock response. The pipeline ran end to end using ${prompt.length} characters of prompt."
            prompt.contains("\"questions\"") -> interviewJson()
            prompt.contains("\"worldLore\"") -> campaignBlueprintJson()
            else -> genericJson(prompt.length)
        }

        // Rough estimate: ~4 characters per token.
        val promptTokens = prompt.length / 4
        val completionTokens = content.length / 4
        return LlmResult(
            content = content,
            usage = TokenUsage(promptTokens, completionTokens, promptTokens + completionTokens),
            model = "mock",
            mocked = true,
        )
    }

    private fun genericJson(promptLength: Int) = """
        {
          "name": "Mock the Placeholder",
          "summary": "Generated by MockLlmClient because no OpenAI key was used.",
          "description": "This response proves the pipeline ran end to end: campaign context was collected, a prompt was built, a client was called, and the reply was validated.",
          "promptCharacters": $promptLength
        }
    """.trimIndent()

    private fun interviewJson() = """
        {
          "understanding": "A mock paraphrase of your idea, produced without calling OpenAI.",
          "questions": [
            {
              "id": "central_conflict",
              "question": "What is the central conflict driving this campaign?",
              "why": "It determines the shape of every quest.",
              "suggestedAnswers": ["A looming invasion", "A political conspiracy", "An awakening ancient evil"]
            },
            {
              "id": "villain_goal",
              "question": "What does the villain actually want?",
              "why": "A concrete goal makes the villain feel active rather than decorative.",
              "suggestedAnswers": ["Immortality", "Revenge on a bloodline", "To rewrite history"]
            },
            {
              "id": "party_stake",
              "question": "Why is this party the one that has to deal with it?",
              "why": "It ties the players personally into the story.",
              "suggestedAnswers": ["They are the only witnesses", "They are blamed for it", "They are bound by an oath"]
            }
          ]
        }
    """.trimIndent()

    private fun campaignBlueprintJson() = """
        {
          "name": "The Mock Campaign",
          "premise": "A placeholder campaign produced without calling OpenAI, so the full pipeline can be tested for free.",
          "worldLore": "This world exists only to prove that generated content is written into Campaign Memory as structured rows. The Ashen Vale is a shuttered valley where a mock cult stirs. Its people remember a fire that never went out, and the roads out lead only back in.",
          "tone": "Testing, faintly ominous",
          "locations": [
            {
              "name": "The Ashen Vale",
              "type": "REGION",
              "description": "A valley of grey fields under a permanently overcast sky.",
              "atmosphere": "Fine ash on every surface; the smell of old smoke.",
              "parentName": null
            },
            {
              "name": "Cinderhollow",
              "type": "VILLAGE",
              "description": "The last inhabited settlement in the vale.",
              "atmosphere": "Shuttered windows and cold hearths.",
              "parentName": "The Ashen Vale"
            }
          ],
          "factions": [
            {
              "name": "The Ember Circle",
              "type": "Cult",
              "description": "Keepers of a fire they will not let die.",
              "goals": "Rekindle the old flame beneath the vale.",
              "ideology": "Ash is only fire that is waiting.",
              "headquartersName": "Cinderhollow"
            }
          ],
          "npcs": [
            {
              "name": "Vessa Coalwright",
              "race": "Human",
              "occupation": "Innkeeper",
              "role": "Quest giver",
              "description": "Runs the only inn still serving hot food.",
              "appearance": "Soot-stained apron, burn scars along both forearms.",
              "personality": "Blunt, generous, tired.",
              "motivation": "Keep Cinderhollow alive one more winter.",
              "secret": "She was once a member of the Ember Circle.",
              "voice": "Low and flat, never wastes a word.",
              "locationName": "Cinderhollow",
              "factionName": null
            },
            {
              "name": "Warden Ilric",
              "race": "Human",
              "occupation": "Cult warden",
              "role": "Villain",
              "description": "Speaks for the Ember Circle in public.",
              "appearance": "Immaculate grey robes that never gather ash.",
              "personality": "Patient, courteous, immovable.",
              "motivation": "Complete the rekindling before the vale empties.",
              "secret": "The rekindling requires the village itself as fuel.",
              "voice": "Warm and reasonable, which is worse.",
              "locationName": "Cinderhollow",
              "factionName": "The Ember Circle"
            }
          ],
          "quests": [
            {
              "title": "The Cold Hearth",
              "description": "Vessa's hearth will not light, and nor will any other in the village.",
              "hook": "The innkeeper offers free lodging to anyone who can explain it.",
              "objective": "Discover why fire no longer takes in Cinderhollow.",
              "reward": "Shelter, supplies, and Vessa's trust.",
              "questGiverName": "Vessa Coalwright",
              "locationName": "Cinderhollow",
              "involvedNpcNames": ["Vessa Coalwright", "Warden Ilric"]
            }
          ],
          "firstSession": {
            "title": "Ash on the Road",
            "summary": "The party arrives in Cinderhollow as the last hearth goes cold.",
            "openingScene": "The ash starts before the border stone. By the time you reach the village gate it is over your boots, and no chimney in sight is smoking.",
            "beats": [
              "Arrival at the village gate and the unnatural silence",
              "Vessa offers food she cannot heat, and asks for help",
              "Warden Ilric introduces himself far too pleasantly",
              "A child is found sleepwalking toward the old furnace"
            ],
            "encounters": [
              "Social: Warden Ilric probes what the party knows",
              "Exploration: the sealed furnace beneath the village"
            ],
            "cliffhanger": "The furnace door is warm to the touch, and something inside knocks back.",
            "dmTips": [
              "Play Ilric as helpful; let the players decide he is wrong.",
              "Keep the cold hearths constant so the payoff lands."
            ]
          }
        }
    """.trimIndent()
}
